CREATE DATABASE DeepDevAI;

USE DeepDevAI;

CREATE TABLE users(
userID INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
userName VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
userPassword VARCHAR(100) NOT NULL
);

